# Generated by Django 5.0.3 on 2024-06-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='episode_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='manga_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='movie_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='中文标题')),
                ('org_title', models.CharField(max_length=30, verbose_name='原始标题')),
                ('alternate_titles', models.CharField(blank=True, default='', max_length=40, verbose_name='译名/其它译名')),
                ('author', models.CharField(default='', max_length=20, verbose_name='作者')),
                ('status', models.CharField(choices=[('SER', '连载中'), ('HIATUS', '停更'), ('COM', '完结'), ('STANDALONE', '独立作品'), ('SIDE', '衍生作品')], default='SER', max_length=10, verbose_name='连载状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('review', models.TextField(blank=True, null=True, verbose_name='我的想法')),
                ('finish', models.BooleanField(default=False, verbose_name='完成阅读')),
                ('myprogress', models.CharField(blank=True, max_length=20, null=True, verbose_name='我的进度')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='Base/manga/pic')),
                ('tags', models.ManyToManyField(blank=True, to='dovahbase.manga_tag', verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='中文标题')),
                ('org_title', models.CharField(max_length=30, verbose_name='原始标题')),
                ('lternate_titles', models.CharField(blank=True, default='', max_length=40, verbose_name='译名/其它译名')),
                ('type', models.CharField(choices=[('ANI', '动画番剧'), ('DOM', '国产剧'), ('EPI', '欧美剧集'), ('DOC', '纪录片'), ('OTH', '其他')], default='ANI', max_length=4, verbose_name='剧集类型')),
                ('tags', models.ManyToManyField(blank=True, to='dovahbase.manga_tag', verbose_name='标签')),
            ],
        ),
    ]
