# Generated by Django 6.0 on 2025-12-20 17:52

import django.core.validators
import dovahbase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='中文标题')),
                ('org_title', models.CharField(max_length=80, verbose_name='原始标题')),
                ('alternate_titles', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='译名/其它译名')),
                ('type', models.CharField(choices=[('动画番剧', '动画番剧'), ('国产剧', '国产剧'), ('欧美剧集', '欧美剧集'), ('纪录片', '纪录片'), ('其他', '其他')], default='动画番剧', max_length=4, verbose_name='剧集类型')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='Base/episode/pic', verbose_name='封面')),
                ('finish', models.BooleanField(default=False, verbose_name='完成观看')),
                ('review', models.TextField(blank=True, null=True, verbose_name='我的想法')),
                ('release_time', models.CharField(max_length=7, validators=[dovahbase.models.validate_year_month], verbose_name='放送时间')),
                ('myprogress', models.CharField(blank=True, max_length=20, null=True, verbose_name='我的进度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resource', models.TextField(blank=True, default='', null=True, verbose_name='资源信息')),
            ],
        ),
        migrations.CreateModel(
            name='manga_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='movie_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='中文标题')),
                ('org_title', models.CharField(max_length=80, verbose_name='原始标题')),
                ('alternate_titles', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='译名/其它译名')),
                ('author', models.CharField(default='', max_length=20, verbose_name='作者')),
                ('status', models.CharField(choices=[('连载中', '连载中'), ('停更', '停更'), ('完结', '完结'), ('独立作品', '独立作品'), ('衍生作品', '衍生作品')], default='连载中', max_length=10, verbose_name='连载状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('review', models.TextField(blank=True, null=True, verbose_name='我的想法')),
                ('finish', models.BooleanField(default=False, verbose_name='完成阅读')),
                ('myprogress', models.CharField(blank=True, max_length=20, null=True, verbose_name='我的进度')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='Base/manga/pic', verbose_name='封面')),
                ('tags', models.ManyToManyField(blank=True, to='dovahbase.manga_tag', verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='中文标题')),
                ('org_title', models.CharField(max_length=80, verbose_name='原始标题')),
                ('alternate_titles', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='译名/其它译名')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='Base/movie/pic', verbose_name='封面')),
                ('review', models.TextField(blank=True, null=True, verbose_name='我的想法')),
                ('release_time', models.IntegerField(validators=[dovahbase.models.validate_year], verbose_name='上映年份')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('watch_date', models.DateField(null=True, verbose_name='观看时间')),
                ('resource', models.TextField(blank=True, default='', null=True, verbose_name='资源信息')),
                ('myrate', models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='我的评分')),
                ('tags', models.ManyToManyField(blank=True, to='dovahbase.movie_tag', verbose_name='标签')),
            ],
        ),
    ]
