# Generated by Django 5.0.3 on 2024-06-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dovahbase", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="episode",
            old_name="lternate_titles",
            new_name="alternate_titles",
        ),
    ]
