# Generated by Django 5.0.3 on 2024-06-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dovahbase', '0002_rename_lternate_titles_episode_alternate_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='type',
            field=models.CharField(choices=[('动画番剧', '动画番剧'), ('国产剧', '国产剧'), ('欧美剧集', '欧美剧集'), ('纪录片', '纪录片'), ('其他', '其他')], default='ANI', max_length=4, verbose_name='剧集类型'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.CharField(choices=[('连载中', '连载中'), ('停更', '停更'), ('完结', '完结'), ('独立作品', '独立作品'), ('衍生作品', '衍生作品')], default='SER', max_length=10, verbose_name='连载状态'),
        ),
    ]
