# Generated by Django 5.0.3 on 2024-07-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dovahbase', '0003_alter_episode_type_alter_manga_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='type',
            field=models.CharField(choices=[('动画番剧', '动画番剧'), ('国产剧', '国产剧'), ('欧美剧集', '欧美剧集'), ('纪录片', '纪录片'), ('其他', '其他')], default='动画番剧', max_length=4, verbose_name='剧集类型'),
        ),
    ]
