# Generated by Django 5.0.3 on 2024-07-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dovahbase",
            "0005_episode_created_at_episode_finish_episode_myprogress_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="tags",
        ),
    ]
