# Generated by Django 5.0.3 on 2024-07-02 09:29

import django.core.validators
import dovahbase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dovahbase", "0006_remove_episode_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="中文标题")),
                ("org_title", models.CharField(max_length=30, verbose_name="原始标题")),
                (
                    "alternate_titles",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="译名/其它译名"
                    ),
                ),
                (
                    "pic",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Base/episode/pic",
                        verbose_name="封面",
                    ),
                ),
                (
                    "review",
                    models.TextField(blank=True, null=True, verbose_name="我的想法"),
                ),
                (
                    "release_time",
                    models.IntegerField(
                        validators=[dovahbase.models.validate_year], verbose_name="上映年份"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("watch_date", models.DateTimeField(verbose_name="观看时间")),
                (
                    "resource",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="资源信息"
                    ),
                ),
                (
                    "myrate",
                    models.IntegerField(
                        default=80,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="我的评分",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="episode_tag",
        ),
    ]
