# Generated by Django 5.0.3 on 2024-07-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dovahbase", "0007_movie_delete_episode_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="watch_date",
            field=models.DateField(verbose_name="观看时间"),
        ),
    ]
