# Generated by Django 5.0.3 on 2024-07-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dovahbase", "0008_alter_movie_watch_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="dovahbase.movie_tag", verbose_name="标签"
            ),
        ),
    ]
