# Generated by Django 5.0.3 on 2024-07-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dovahbase", "0009_movie_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="alternate_titles",
            field=models.CharField(
                blank=True, default="", max_length=40, null=True, verbose_name="译名/其它译名"
            ),
        ),
        migrations.AlterField(
            model_name="manga",
            name="alternate_titles",
            field=models.CharField(
                blank=True, default="", max_length=40, null=True, verbose_name="译名/其它译名"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="alternate_titles",
            field=models.CharField(
                blank=True, default="", max_length=40, null=True, verbose_name="译名/其它译名"
            ),
        ),
    ]
