# Generated by Django 5.0.3 on 2024-07-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dovahbase", "0010_alter_episode_alternate_titles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="alternate_titles",
            field=models.CharField(
                blank=True, default="", max_length=80, null=True, verbose_name="译名/其它译名"
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="org_title",
            field=models.CharField(max_length=50, verbose_name="原始标题"),
        ),
        migrations.AlterField(
            model_name="episode",
            name="title",
            field=models.CharField(max_length=50, verbose_name="中文标题"),
        ),
        migrations.AlterField(
            model_name="manga",
            name="alternate_titles",
            field=models.CharField(
                blank=True, default="", max_length=80, null=True, verbose_name="译名/其它译名"
            ),
        ),
        migrations.AlterField(
            model_name="manga",
            name="org_title",
            field=models.CharField(max_length=50, verbose_name="原始标题"),
        ),
        migrations.AlterField(
            model_name="manga",
            name="title",
            field=models.CharField(max_length=50, verbose_name="中文标题"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="alternate_titles",
            field=models.CharField(
                blank=True, default="", max_length=80, null=True, verbose_name="译名/其它译名"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="org_title",
            field=models.CharField(max_length=50, verbose_name="原始标题"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=50, verbose_name="中文标题"),
        ),
    ]
