# Generated by Django 5.0.3 on 2024-07-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dovahbase', '0012_alter_movie_watch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='alternate_titles',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='译名/其它译名'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='org_title',
            field=models.CharField(max_length=80, verbose_name='原始标题'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='alternate_titles',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='译名/其它译名'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='org_title',
            field=models.CharField(max_length=80, verbose_name='原始标题'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='alternate_titles',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='译名/其它译名'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='org_title',
            field=models.CharField(max_length=80, verbose_name='原始标题'),
        ),
    ]
