# Generated by Django 6.0 on 2025-12-20 17:26

import dovahride.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='标题')),
                ('data_file', models.FileField(upload_to=dovahride.models.ride_file_path, verbose_name='数据文件')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=dovahride.models.ride_thumb_path, verbose_name='缩略图')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('total_distance', models.FloatField(default=0, verbose_name='里程(km)')),
                ('total_duration', models.IntegerField(default=0, verbose_name='总耗时(s)')),
                ('moving_time', models.IntegerField(default=0, verbose_name='骑行时间(s)')),
                ('total_ascent', models.FloatField(default=0, verbose_name='爬升(m)')),
                ('avg_speed', models.FloatField(default=0, verbose_name='均速(km/h)')),
                ('max_speed', models.FloatField(default=0, verbose_name='极速(km/h)')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='卡路里')),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True, verbose_name='平均心率')),
                ('avg_power', models.IntegerField(blank=True, null=True, verbose_name='平均功率')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
